#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branch:
      only:
        - main
    docker:
      # specify the version you desire here
      - image: circleci/node:16.13.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo
    

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run clean
      - run: npm run build
      - add_ssh_keys:
              fingerprints: 
                - "1a:d3:ae:d9:d5:b9:58:26:a6:ad:0e:bd:9d:d2:60:39"    
      - deploy:
          command: |
            git config --global user.email circle@qq.com
            git config --global user.name circleci
            npm run deploy